appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RyVy9j5JCicFM7GepPmGyinNbnoJFEiAbQAIphSN9ef8YRDmTx4tV4pP6b0oGAPcWlZ/c/0hkYqrDVFfkt6Tri/HDR358DGAXAu3IPRPrY9uu/t52C5gtqoD28f6BA/6mWbRmFZQS5FwTBq88FvTpKZVpLt4X/FFrOVUWFjEWt14/lJw8+xnL63XPGMSNZG0tDNkNFyKmWQV9w2mmXtYbjt9iFQwqn/EJ+vcDzDFlZKvsqId69OFh7s1RYQ3ZI3swrKBj2mpWzsS+JF1N4DyaTlfU8Z8Ux3LPpwR2TXoyXqV/0+6FbcpwH9R93x0Gr211jnQaO3j/puvi7a2CPzmlZs0vO095JEOUV6ICRV8ml1x91dX9QUdJ8IRgx5TJc3MV/WbLcEze6Nc1RMH4ItrQ1AY0o3/oAtF4+HsesRoH+uNGVUmZl4RobOnIHxLUh4cD9S1FUZgVmmfk6BWZqCmOpUDiDRJkxCQDKjkzOTpM7ycf6A+9AC8STKGGAIKPmcOipF9XEwqc/Zkki3u7ipW8J7P0eQZwR8vsMwK9xAhApwX13CA/UuzOqmRTdmBvLFtnQIApmn4EcwI6+E/8dpWuMBYGdxnpAdEx/SRf7XCIIb8z1llpdETmcjzbcedp4Nj+0eV8+Dj1Trk6xWHLqLIo4y70LgqlM0u+EtWBTpTxXg=}
